apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "faq.fullname" . }}
  labels:
    app: {{ template "faq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  debug.sh: {{ .Values.debug }}