# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "faq.fullname" . }}
  labels:
    app: {{ template "faq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.port }}
      nodePort: {{ .Values.service.ports.nodePort }}
  selector:
    app: {{ template "faq.fullname" . }}