{{ if .Values.logdna.agentKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.logdna.name }}
  labels:
        {{ include "faq.labels" . | indent 4 }}
type: Opaque
data:
  logdna-agent-key: {{  .Values.logdna.agentKey | b64enc | quote }}
{{ end }}
  