# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "faq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "faq.name" . }}
    helm.sh/chart: {{ include "faq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.port }}
      nodePort: {{ .Values.service.ports.nodePort }}
  selector:
    app: {{ template "faq.fullname" . }}
